server:
  port: 8090
spring:
  application:
    name: user-account-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user_account_db
    username: extrade_user
    password: extrade@1
  jpa:
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: srimanodwa4@gmail.com
    password: dmct lscu xyrx phyg
    properties:
      mail.smtp.ssl.trust: smtp.gmail.com
      mail.smtp.starttls.enable: true
      mail.smtp.auth: true
  thymeleaf:
    prefix: file:///${eXtrade.template.dir}

logging:
  level:
    root: info
  logback:
    rollingpolicy:
      file-name-pattern: /var/log/xtrade-user-account-%d{yyyy-MM-dd}.%i.log
      max-file-size: 10MB
      max-history: 30
      total-size-cap: 100GB

springdoc:
  api-docs:
    enabled: true
    path: /apidoc
  swagger-ui:
    path: /swaggerui.html
    enabled: true


eXtrade:
  template:
    dir: ${user.home}/projectworkspace/templates/
  customer:
    weblink: http://localhost:8088/



